{% set name = "mostlyai-engine" %}
{% set version = "1.4.7" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mostlyai_engine-{{ version }}.tar.gz
  sha256: bebbc8e0ed09625c4c3bd8a5db195ca95b7fcd42c3b2fd8bb2a8dace930d7ebe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - setuptools >=77.0.3
    - numpy >=2.0.0
    - pandas >=2.2.0,<2.3.dev0
    - pyarrow >=16.0.0
    - joblib >=1.4.2
    - psutil >=5.9.5,<6
    - tokenizers >=0.21.0
    - transformers >=4.51.0
    - datasets >=3.0.0
    - accelerate >=1.5.0
    - peft >=0.12.0
    - huggingface_hub >=0.30.2
    - opacus >=1.5.4
    - xgrammar >=0.1.19
    - json-repair >=0.30.0,<0.47.0
    - pytorch >=2.7.0,<2.7.1
    - torchaudio >=2.7.0,<2.7.1
    - torchvision >=0.22.0,<0.22.1

test:
  imports:
    - mostlyai.engine
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Synthetic Data Engine
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/mostly-ai/mostlyai-engine

extra:
  recipe-maintainers:
    - AndreasAlbertQC
